### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by laohuan12138** [m-sec-org/EZ#9]
每次都是扫着扫着报这个错误，不知道啥原因
`goroutine 6836941 [select]:
runtime.gopark(0xc03ef39f90?, 0x2?, 0xd8?, 0x9d?, 0xc03ef39f24?)
        runtime/proc.go:363 +0xd6 fp=0xc03ef39d90 sp=0xc03ef39d70 pc=0x7ff651604536
runtime.selectgo(0xc03ef39f90, 0xc03ef39f20, 0xc03ed6a040?, 0x0, 0xc0084fb0e0?, 0x1)
        runtime/select.go:328 +0x7dc fp=0xc03ef39ed0 sp=0xc03ef39d90 pc=0x7ff6516140bc
net/http.(*persistConn).writeLoop(0xc03ce20900)
        net/http/transport.go:2392 +0xf5 fp=0xc03ef39fc8 sp=0xc03ef39ed0 pc=0x7ff651a3ef95
net/http.(*Transport).dialConn.func6()
        net/http/transport.go:1752 +0x26 fp=0xc03ef39fe0 sp=0xc03ef39fc8 pc=0x7ff651a3ba86
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc03ef39fe8 sp=0xc03ef39fe0 pc=0x7ff6516350e1
created by net/http.(*Transport).dialConn
        net/http/transport.go:1752 +0x1791

goroutine 6837017 [runnable]:
net/http.(*Transport).dialConn.func6()
        net/http/transport.go:1752 fp=0xc03c6dbfe0 sp=0xc03c6dbfd8 pc=0x7ff651a3ba60
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc03c6dbfe8 sp=0xc03c6dbfe0 pc=0x7ff6516350e1
created by net/http.(*Transport).dialConn
        net/http/transport.go:1752 +0x1791`

**Comment by 1oid** [comment]
有具体的扫描参数吗，我们本地复测下

**Comment by laohuan12138** [comment]
除了子域名发现，其他的全勾上，包括poc，全端口扫描，扫描数量在200个左右IP地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "m-sec-org/EZ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [m-sec-org/EZ] 运行报错 (Issue #9)





 
有具体的扫描参数吗，我们本地复测下

**Comment by 1oid** [comment]
如果用的是Linux，跑ez的时候用./ez -l debug web来起，并且使用nohup来搜集下输出日志。你上面发的这段报错信息没有包含主要的报错信息，不太好排查。

**Comment by laohuan12138** [comment]
我用的是windows报的错误，能用这个参数吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "m-sec-org/EZ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [m-sec-org/EZ] 运行报错 (Issue #9)





 
如果用的是Linux，跑ez的时候用./ez -l debug web来起，并且使用nohup来搜集下输出日志。你上面发的这段报错信息没有包含主要的报错信息，不太好排查。

**Comment by 1oid** [comment]
windows下也可以通过 ez.exe -l debug web来起，不过运行日志保存，你得看下有没有稳定点的搜集方式，一般来说重定向输出到文件就OK，比如 xxx.exe > save_log.txt

**Comment by laohuan12138** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月5日(星期四) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [m-sec-org/EZ] 运行报错 (Issue #9)














 
windows下也可以通过 ez.exe -l debug web来起，不过运行日志保存，你得看下有没有稳定点的搜集方式，一般来说重定向输出到文件就OK，比如 xxx.exe &gt; save_log.txt
